# Site settings
title: The Next Billion Online
email: contact@thenextbillion.online
url: http://thenextbillion.online/
description: "Technology brings bounty to the rich, while more than half of the world lacks basic access to the internet. The only way to fix that is with an intersectional analysis that targets the root causes of these disparities. All human beings have a right to communicate freely, openly, and securely, regardless of their sex, gender, race, or class. Technological liberation is rooted in grass-roots action, open source code, and the technologies to keep people safely in touch, wherever they may be."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#3e486d'
  links: '#7792f5'

# Footer settings
footer: The Next Billion Online

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/rojavatechops/thenextbillion.online

# Build settings
markdown: kramdown
permalink: pretty
