# Site settings
title: The Next Billion Online
email: contact@thenextbillion.online
url: http://thenextbillion.online/
description: "The technologies we take for granted in industrialized places stand to elevate populations globally. However, more than half of the world lacks basic access to the internet. With open-source tools, software, and educational materials, we can change that. One router, one satellite dish at a time."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#8f8f8f'
  links: '#1D3A83'

# Footer settings
footer: The Next Billion Online

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/rojavatechops/thenextbillion.online

# Build settings
markdown: kramdown
permalink: pretty

